# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - pip install .
    - pip install -r docs/doc-requirements.txt
    - sphinx-build -M html docs docs/_build
    - sphinx-build -M simplepdf docs docs/_build
    - cp docs/_build/simplepdf/Sphinx-SimplePDF.pdf docs/_build/html/_static/Sphinx-SimplePDF.pdf
    - mkdir -p _readthedocs/html/
    - cp -r docs/_build/html/* _readthedocs/html/
#  jobs:
#    post_build:
#      - sphinx-build -M simplepdf docs docs/_build
#      - ls -la docs/_build/simplepdf/
#      - cp -f docs/_build/simplepdf/Sphinx-SimplePDF.pdf docs/_build/html/_static/Sphinx-SimplePDF.pdf
#      - ls -la docs/_build/html/_static/
#      - ls -la docs
#      - ls -la docs/_build
#      - ls -la .

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/doc-requirements.txt
   - method: pip
     path: .