# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  # We can only define the content of the final deployment, if we do the complete build on our own.apt_packages:
  # So we need to handle package installation, build start and copying the right files for deployment.
  commands:
    - pip install .
    - pip install -r docs/doc-requirements.txt
    - sphinx-build -M html docs docs/_build
    - sphinx-build -M simplepdf docs docs/_build
    - cp docs/_build/simplepdf/Sphinx-SimplePDF.pdf docs/_build/html/_static/Sphinx-SimplePDF.pdf
    - mkdir -p _readthedocs/html/
    - cp -r docs/_build/html/* _readthedocs/html/

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/doc-requirements.txt
   - method: pip
     path: .